"""
CQL ELM Evaluators Package

This package contains evaluators for all CQL expression types, organized by category:

- temporal: Date, DateTime, Time operations and temporal comparisons
- interval_ops: Interval construction and operations
- list_ops: List manipulation and operations
- aggregate: Aggregate functions (sum, count, min, max, etc.)
- query: Query expressions and filtering
- definitions: Expression/function definitions and references
- clinical: Clinical operations (value sets, codes, retrieve)
- obfuscate: PHI obfuscation/de-identification
"""

# Temporal evaluators
from .temporal import (
    DateEvaluator,
    DateTimeEvaluator,
    TimeEvaluator,
    NowEvaluator,
    TodayEvaluator,
    TimeOfDayEvaluator,
    DateFromEvaluator,
    TimeFromEvaluator,
    DateTimeComponentFromEvaluator,
    TimezoneOffsetFromEvaluator,
    DurationBetweenEvaluator,
    DifferenceBetweenEvaluator,
    BeforeEvaluator,
    AfterEvaluator,
    SameAsEvaluator,
    SameOrBeforeEvaluator,
    SameOrAfterEvaluator,
)

# Interval evaluators
from .interval_ops import (
    IntervalEvaluator,
    StartEvaluator,
    EndEvaluator,
    ContainsEvaluator,
    InEvaluator,
    IncludesEvaluator,
    IncludedInEvaluator,
    ProperContainsEvaluator,
    ProperInEvaluator,
    ProperIncludesEvaluator,
    ProperIncludedInEvaluator,
    MeetsEvaluator,
    MeetsBeforeEvaluator,
    MeetsAfterEvaluator,
    OverlapsEvaluator,
    OverlapsBeforeEvaluator,
    OverlapsAfterEvaluator,
    CollapseEvaluator,
    ExpandEvaluator,
    WidthEvaluator,
    SizeEvaluator,
    PointFromEvaluator,
)

# List evaluators
from .list_ops import (
    ListEvaluator,
    ExistsEvaluator,
    UnionEvaluator,
    IntersectEvaluator,
    ExceptEvaluator,
    DistinctEvaluator,
    FlattenEvaluator,
    SingletonFromEvaluator,
    IndexerEvaluator,
    FirstEvaluator,
    LastEvaluator,
    SliceEvaluator,
    CurrentEvaluator,
    RepeatEvaluator,
)

# Aggregate evaluators
from .aggregate import (
    CountEvaluator,
    SumEvaluator,
    MinEvaluator,
    MaxEvaluator,
    AvgEvaluator,
    MedianEvaluator,
    ModeEvaluator,
    VarianceEvaluator,
    StdDevEvaluator,
    PopulationVarianceEvaluator,
    PopulationStdDevEvaluator,
    AllTrueEvaluator,
    AnyTrueEvaluator,
    GeometricMeanEvaluator,
    ProductEvaluator,
)

# Query evaluators
from .query import (
    QueryExpressionEvaluator,
    AliasedQuerySourceEvaluator,
    QueryLetRefEvaluator,
    AliasRefEvaluator,
    WithEvaluator,
    WithoutEvaluator,
    WhereEvaluator,
    ReturnEvaluator,
    SortEvaluator,
    SortClauseEvaluator,
    ByDirectionEvaluator,
    ByColumnEvaluator,
    ByExpressionEvaluator,
    ForEachEvaluator,
    FilterEvaluator,
    TimesEvaluator,
)

# Definition evaluators
from .definitions import (
    ExpressionDefEvaluator,
    FunctionDefEvaluator,
    FunctionRefEvaluator,
    ExpressionRefEvaluator,
    OperandRefEvaluator,
    ParameterRefEvaluator,
    ParameterDefEvaluator,
    IdentifierRefEvaluator,
    PropertyEvaluator,
    TupleEvaluator,
    TupleElementEvaluator,
    InstanceEvaluator,
    LiteralEvaluator,
    QuantityEvaluator,
    RatioEvaluator,
    CodeEvaluator,
    ConceptEvaluator,
    MessageEvaluator,
    TotalEvaluator,
)

# Clinical evaluators
from .clinical import (
    RetrieveEvaluator,
    CodeSystemRefEvaluator,
    ValueSetRefEvaluator,
    CodeRefEvaluator,
    ConceptRefEvaluator,
    InValueSetEvaluator,
    InCodeSystemEvaluator,
    AnyInValueSetEvaluator,
    AnyInCodeSystemEvaluator,
    ExpandValueSetEvaluator,
    CalculateAgeEvaluator,
    CalculateAgeAtEvaluator,
)

# Obfuscation evaluators
from .obfuscate import (
    PHIObfuscator,
    NoOpPHIObfuscator,
    RedactingPHIObfuscator,
    MaskingPHIObfuscator,
    PartialMaskingPHIObfuscator,
    create_obfuscator,
    PHIObfuscationContext,
)

__all__ = [
    # Temporal
    'DateEvaluator',
    'DateTimeEvaluator',
    'TimeEvaluator',
    'NowEvaluator',
    'TodayEvaluator',
    'TimeOfDayEvaluator',
    'DateFromEvaluator',
    'TimeFromEvaluator',
    'DateTimeComponentFromEvaluator',
    'TimezoneOffsetFromEvaluator',
    'DurationBetweenEvaluator',
    'DifferenceBetweenEvaluator',
    'BeforeEvaluator',
    'AfterEvaluator',
    'SameAsEvaluator',
    'SameOrBeforeEvaluator',
    'SameOrAfterEvaluator',
    # Interval
    'IntervalEvaluator',
    'StartEvaluator',
    'EndEvaluator',
    'ContainsEvaluator',
    'InEvaluator',
    'IncludesEvaluator',
    'IncludedInEvaluator',
    'ProperContainsEvaluator',
    'ProperInEvaluator',
    'ProperIncludesEvaluator',
    'ProperIncludedInEvaluator',
    'MeetsEvaluator',
    'MeetsBeforeEvaluator',
    'MeetsAfterEvaluator',
    'OverlapsEvaluator',
    'OverlapsBeforeEvaluator',
    'OverlapsAfterEvaluator',
    'CollapseEvaluator',
    'ExpandEvaluator',
    'WidthEvaluator',
    'SizeEvaluator',
    'PointFromEvaluator',
    # List
    'ListEvaluator',
    'ExistsEvaluator',
    'UnionEvaluator',
    'IntersectEvaluator',
    'ExceptEvaluator',
    'DistinctEvaluator',
    'FlattenEvaluator',
    'SingletonFromEvaluator',
    'IndexerEvaluator',
    'FirstEvaluator',
    'LastEvaluator',
    'SliceEvaluator',
    'CurrentEvaluator',
    'RepeatEvaluator',
    # Aggregate
    'CountEvaluator',
    'SumEvaluator',
    'MinEvaluator',
    'MaxEvaluator',
    'AvgEvaluator',
    'MedianEvaluator',
    'ModeEvaluator',
    'VarianceEvaluator',
    'StdDevEvaluator',
    'PopulationVarianceEvaluator',
    'PopulationStdDevEvaluator',
    'AllTrueEvaluator',
    'AnyTrueEvaluator',
    'GeometricMeanEvaluator',
    'ProductEvaluator',
    # Query
    'QueryExpressionEvaluator',
    'AliasedQuerySourceEvaluator',
    'QueryLetRefEvaluator',
    'AliasRefEvaluator',
    'WithEvaluator',
    'WithoutEvaluator',
    'WhereEvaluator',
    'ReturnEvaluator',
    'SortEvaluator',
    'SortClauseEvaluator',
    'ByDirectionEvaluator',
    'ByColumnEvaluator',
    'ByExpressionEvaluator',
    'ForEachEvaluator',
    'FilterEvaluator',
    'TimesEvaluator',
    # Definition
    'ExpressionDefEvaluator',
    'FunctionDefEvaluator',
    'FunctionRefEvaluator',
    'ExpressionRefEvaluator',
    'OperandRefEvaluator',
    'ParameterRefEvaluator',
    'ParameterDefEvaluator',
    'IdentifierRefEvaluator',
    'PropertyEvaluator',
    'TupleEvaluator',
    'TupleElementEvaluator',
    'InstanceEvaluator',
    'LiteralEvaluator',
    'QuantityEvaluator',
    'RatioEvaluator',
    'CodeEvaluator',
    'ConceptEvaluator',
    'MessageEvaluator',
    'TotalEvaluator',
    # Clinical
    'RetrieveEvaluator',
    'CodeSystemRefEvaluator',
    'ValueSetRefEvaluator',
    'CodeRefEvaluator',
    'ConceptRefEvaluator',
    'InValueSetEvaluator',
    'InCodeSystemEvaluator',
    'AnyInValueSetEvaluator',
    'AnyInCodeSystemEvaluator',
    'ExpandValueSetEvaluator',
    'CalculateAgeEvaluator',
    'CalculateAgeAtEvaluator',
    # Obfuscation
    'PHIObfuscator',
    'NoOpPHIObfuscator',
    'RedactingPHIObfuscator',
    'MaskingPHIObfuscator',
    'PartialMaskingPHIObfuscator',
    'create_obfuscator',
    'PHIObfuscationContext',
]
