#!/usr/bin/env python3
"""Generate a Python port scaffold from Java source files.

This creates a module tree under python/cql_engine that mirrors Java package names,
with class and method stubs to accelerate manual migration.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIRS = [
    ROOT / "engine/src/main/java",
    ROOT / "engine.jackson/src/main/java",
]
OUT_ROOT = ROOT / "python/cql_engine"

PACKAGE_RE = re.compile(r"^\s*package\s+([\w.]+)\s*;", re.MULTILINE)
CLASS_RE = re.compile(r"\b(class|interface|enum)\s+([A-Z][A-Za-z0-9_]*)")
METHOD_RE = re.compile(
    r"^\s*(?:public|protected|private)?\s*(?:static\s+)?(?:final\s+)?[\w<>, ?\[\]]+\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(([^)]*)\)\s*(?:throws\s+[^{]+)?\{?\s*$",
    re.MULTILINE,
)
SKIP_METHODS = {"if", "for", "while", "switch", "catch", "return", "new"}
PY_KEYWORDS = {"and", "or", "not", "in", "is", "except", "from", "class", "global", "pass", "with", "as", "lambda", "def", "return", "yield", "await", "async", "import", "raise", "try", "finally", "else", "elif", "if", "for", "while"}


def py_params(java_params: str) -> str:
    if not java_params.strip():
        return "self"
    params = [p.strip() for p in java_params.split(",") if p.strip()]
    names = []
    for p in params:
        tokens = p.replace("...", " ").split()
        if not tokens:
            continue
        name = tokens[-1].replace("[]", "").strip()
        name = re.sub(r"[^A-Za-z0-9_]", "", name)
        if not name:
            continue
        if name in {"from", "class", "global", "pass", "type"}:
            name = f"{name}_"
        names.append(name)
    return ", ".join(["self", *names])


def convert_file(java_file: Path) -> None:
    text = java_file.read_text(encoding="utf-8", errors="ignore")
    package_match = PACKAGE_RE.search(text)
    package = package_match.group(1) if package_match else ""

    rel_dir = Path(*package.split(".")) if package else Path()
    out_dir = OUT_ROOT / rel_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "__init__.py").touch(exist_ok=True)

    classes = CLASS_RE.findall(text)
    methods = METHOD_RE.findall(text)

    out_file = out_dir / f"{java_file.stem}.py"
    lines = [
        '"""Auto-generated Python scaffold from Java source.',
        "",
        f"Source: {java_file.relative_to(ROOT)}",
        '"""',
        "",
    ]

    if classes:
        emitted_any = False
        for _, class_name in classes:
            lines.append(f"class {class_name}:")
            class_methods = []
            for m_name, m_params in methods:
                if m_name in SKIP_METHODS or m_name[0].isupper():
                    continue
                class_methods.append((m_name, m_params))
            if class_methods:
                emitted_any = True
                seen = set()
                for m_name, m_params in class_methods:
                    if m_name in seen:
                        continue
                    seen.add(m_name)
                    params = py_params(m_params)
                    py_name = f"{m_name}_" if m_name in PY_KEYWORDS else m_name
                    lines.append(f"    def {py_name}({params}):")
                    lines.append(
                        '        raise NotImplementedError("Port from Java implementation is pending")'
                    )
                    lines.append("")
            else:
                lines.append("    pass")
                lines.append("")
        if not emitted_any and lines[-1] != "":
            lines.append("")
    else:
        lines.append("# No class declarations detected; manual port required.")

    out_file.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    count = 0
    for src in SRC_DIRS:
        for java_file in src.rglob("*.java"):
            convert_file(java_file)
            count += 1

    readme = ROOT / "python/README.md"
    readme.parent.mkdir(parents=True, exist_ok=True)
    readme.write_text(
        "# Python Port Scaffold\n\n"
        "This directory contains an auto-generated Python scaffold mirroring Java packages from the original CQL engine.\n\n"
        "- Generated by `scripts/convert_java_to_python.py`.\n"
        "- Methods intentionally raise `NotImplementedError` until manually ported.\n"
        "- The scaffold is meant to accelerate incremental migration, not provide full runtime parity yet.\n",
        encoding="utf-8",
    )

    init_file = ROOT / "python/cql_engine/__init__.py"
    init_file.parent.mkdir(parents=True, exist_ok=True)
    init_file.touch(exist_ok=True)
    print(f"Generated scaffold for {count} Java files")


if __name__ == "__main__":
    main()
